# Generated by Django 3.2.8 on 2021-10-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='icon',
            field=models.ImageField(default='icons/Gromp.png', upload_to='', verbose_name='icon'),
        ),
    ]
