# Generated by Django 3.2.8 on 2021-11-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20211129_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='activation_key',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
