# Generated by Django 3.2.8 on 2021-12-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_player_activation_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.PositiveSmallIntegerField(default=18, verbose_name='age'),
        ),
    ]
