# Generated by Django 3.2.8 on 2021-12-06 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from authapp.models import Player, PlayerProfile


def create_profiles():
    for user in Player.objects.all():
        if not user.playerprofile:
            PlayerProfile.objects.create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_player_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='PLayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField(verbose_name='about me')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, verbose_name='gender')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_profiles)
    ]
